repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        exclude: ^dev-diary\.txt$
      - id: end-of-file-fixer
        exclude: ^dev-diary\.txt$
      - id: check-merge-conflict
      - id: check-ast
      - id: debug-statements
      - id: check-toml
      - id: check-yaml
      - id: check-json
      - id: detect-private-key
      - id: check-added-large-files
      - id: name-tests-test
        args: ["--pytest-test-first"]
        exclude: ^tests/helpers/

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.0
    hooks:
      - id: ruff-check
        args: [ --fix ]
      - id: ruff-format

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.405
    hooks:
      - id: pyright
        args: [--project, pyrightconfig.precommit.json]

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest --cov=src --cov-report=term-missing --cov-fail-under=100
        language: system
        pass_filenames: false
        always_run: true
        types: [python]
